
void Animation_4(){
for (int i = 0; i < 300; i++){
digitalWrite(led[0],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 290; i++){
digitalWrite(led[1],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[1],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[1],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 280; i++){
digitalWrite(led[2],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[2],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[2],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 270; i++){
digitalWrite(led[5],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[5],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[5],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 260; i++){
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 250; i++){
digitalWrite(led[7],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[7],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[7],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 240; i++){
digitalWrite(led[6],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[6],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[6],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 230; i++){
digitalWrite(led[3],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 220; i++){
digitalWrite(led[0],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 210; i++){
digitalWrite(led[1],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[1],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[1],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 200; i++){
digitalWrite(led[2],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[2],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[2],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 190; i++){
digitalWrite(led[5],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[5],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[5],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 180; i++){
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 170; i++){
digitalWrite(led[7],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[7],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[7],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 160; i++){
digitalWrite(led[6],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[6],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[6],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 150; i++){
digitalWrite(led[3],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 140; i++){
digitalWrite(led[0],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 130; i++){
digitalWrite(led[1],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[1],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[1],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 120; i++){
digitalWrite(led[2],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[2],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[2],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 110; i++){
digitalWrite(led[5],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[5],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[5],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 100; i++){
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 90; i++){
digitalWrite(led[7],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[7],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[7],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 80; i++){
digitalWrite(led[6],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[6],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[6],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[3],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 50; i++){
digitalWrite(led[0],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 50; i++){
digitalWrite(led[1],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[1],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[1],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 50; i++){
digitalWrite(led[2],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[2],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[2],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 60; i++){
digitalWrite(led[5],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[5],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[5],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 60; i++){
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[7],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[7],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[7],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[6],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[6],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[6],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[3],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[0],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < 70; i++){
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
}

