
void Animation_11(){
for (int i = 0; i < wied; i++){
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[0],HIGH);
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < wied; i++){
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[1],HIGH);
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < wied; i++){
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[2],HIGH);
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < wied; i++){
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[5],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < wied; i++){
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(led[8],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < wied; i++){
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(led[7],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < wied; i++){
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(led[6],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < wied; i++){
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[3],HIGH);
digitalWrite(led[4],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < wied; i++){
digitalWrite(led[4],HIGH);
digitalWrite(row[0],HIGH);
reset();
digitalWrite(led[4],HIGH);
digitalWrite(row[1],HIGH);
reset();
digitalWrite(led[4],HIGH);
digitalWrite(row[2],HIGH);
clear_all();
}
for (int i = 0; i < wied; i++){
reset();
reset();
clear_all();
}
}

